In [1]:
#============================================================ #
#                Initialising Tensors                         #
#============================================================ #


In [2]:
import torch

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [15]:
my_tensor = torch.tensor([[1, 2, 3],
                          [4, 5, 6]], dtype=torch.float32,
                         device=device, requires_grad=True)

print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
torch.float32
cpu
torch.Size([2, 3])
True


In [23]:
x = torch.empty(size=(3,3))
print(x)
x = torch.rand((3, 3))
print(x)
x = torch.ones((3, 3))
print(x)
x = torch.eye(5, 5)
print(x)
x = torch.zeros((5, 5))
print(x)

x = torch.empty(size=(3,3)).normal_(mean=0, std=1)
print(x)

tensor([[1.4610e+02, 3.1839e-41, 1.4756e+02],
        [3.1839e-41, 2.3694e-38, 2.3694e-38],
        [1.0842e-19, 0.0000e+00, 6.7262e-44]])
tensor([[0.6781, 0.0368, 0.4409],
        [0.4793, 0.4404, 0.2458],
        [0.3216, 0.2186, 0.1856]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[-0.8989, -0.5362,  0.9287],
        [-0.9179, -1.0780,  0.7608],
        [-0.3559,  0.2427, -0.0482]])


In [28]:
tensor = torch.arange(4)
print(tensor.bool())
print(tensor.short())
print(tensor.long())
print(tensor.half())
print(tensor.float())
print(tensor.double())

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [30]:
import numpy as np

array = np.zeros((5, 5))

tensor = torch.from_numpy(array)
print(tensor)

np_arr_back = tensor.numpy()
print(np_arr_back)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Tensor math

In [31]:
x, y = torch.tensor([1, 2, 3]), torch.tensor([9, 8, 7])

In [32]:
z1 = torch.empty(3)
torch.add(x, y, out=z1)
z2 = torch.add(x, y)

z = x+ y
print(z1)
print(z2)
print(z)


tensor([10., 10., 10.])
tensor([10, 10, 10])
tensor([10, 10, 10])


In [33]:
z = x - y
print(z)

tensor([-8, -6, -4])


In [34]:
z = torch.true_divide(x, y)
print(z)

tensor([0.1111, 0.2500, 0.4286])


In [5]:
x =torch.arange(10)
print(x.shape)
print(x.unsqueeze(0).shape)

torch.Size([10])
torch.Size([1, 10])


In [8]:
print(x.squeeze(0).shape)

torch.Size([10])


In [ ]:
#============================================================ #
#                Building a simple Full Connected Network     #
#============================================================ #

In [4]:
# Import all the necessary librairies

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader
import torchvision.datasets as datasets
import torchvision.transforms as transforms


In [7]:
# Create our simple fully connected net
class NN(nn.Module):
  def __init__(self, input_size, num_classes):
    super(NN, self).__init__()
    self.fc1 = nn.Linear(input_size, 50)
    self.fc2 = nn.Linear(50, num_classes)

  def forward(self, x):
    x = F.relu(self.fc1(x))
    x = self.fc2(x)
    return x


In [11]:
model = NN(784, 10)

x = torch.rand(64, 784)

print(model(x).shape)


torch.Size([64, 10])


In [18]:

# Set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# Hyperparams
learning_rate = 0.001
BATCH_SIZE = 64
EPOCHS = 1
num_classes = 10
input_size = 28*28


In [13]:
# Load Data
train_dataset = datasets.MNIST(root='datasets/', train=True, transform=transforms.ToTensor(), download=True)
train_loader = DataLoader(dataset=train_dataset, shuffle=True, batch_size=BATCH_SIZE)
test_dataset = datasets.MNIST(root='datasets/', train=False, transform=transforms.ToTensor(), download=True)
test_loader = DataLoader(dataset=test_dataset, shuffle=True, batch_size=BATCH_SIZE)


Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 9.91M/9.91M [00:00<00:00, 15.9MB/s]


Extracting datasets/MNIST/raw/train-images-idx3-ubyte.gz to datasets/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 28.9k/28.9k [00:00<00:00, 486kB/s]


Extracting datasets/MNIST/raw/train-labels-idx1-ubyte.gz to datasets/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 1.65M/1.65M [00:00<00:00, 4.46MB/s]


Extracting datasets/MNIST/raw/t10k-images-idx3-ubyte.gz to datasets/MNIST/raw

Failed to download (trying next):
HTTP Error 403: Forbidden



100%|██████████| 4.54k/4.54k [00:00<00:00, 2.89MB/s]

Extracting datasets/MNIST/raw/t10k-labels-idx1-ubyte.gz to datasets/MNIST/raw



In [19]:

# Initialize the net
model = NN(input_size=input_size, num_classes=num_classes).to(device)


In [20]:
# Define Loss and Optimizer
criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(model.parameters(), lr=learning_rate)


In [26]:
# Train
for epoch in range(EPOCHS):
  for batch_idx, (data, targets) in enumerate(train_loader):
    #using cuda if possible
    data = data.to(device=device)
    targets = targets.to(device=device)
    #resaping to the correct shape
    data = data.reshape(data.shape[0], -1)

    #forward pass
    scores = model(data)
    loss = criterion(scores, targets)
    #Backward
    optimizer.zero_grad()
    loss.backward()
    #gradientDesc step
    optimizer.step()


In [31]:
# Check score accuracy
def accuracy_score(loader, model):
  if loader.dataset.train:
    print("Checking accuracy on training data")
  else:
    print("Checking accuracy on test data")

  num_correct = 0
  num_sample = 0
  model.eval()

  with torch.no_grad():
    for x, y in loader:
      x = x.to(device=device)
      y = y.to(device=device)
      x = x.reshape(x.shape[0], -1)

      scores = model(x)

      _, predictions = scores.max(1)
      num_correct += (predictions==y).sum()
      num_sample += predictions.size(0)

    acc = float(num_correct)/float(num_sample)*100
    print(f"Got {num_correct}/{num_sample} with accuracy {float(num_correct)/float(num_sample)*100:.2f}")

  model.train()
  # return acc

accuracy_score(train_loader, model)

accuracy_score(test_loader, model)


Checking accuracy on training data
Got 56003/60000 with accuracy 93.34
Checking accuracy on test data
Got 9327/10000 with accuracy 93.27
